Repository PharmaTechVe/dashboard, pull requests merged in 2025-05, with the labels that each got.

#29 Refactor(branches, user, generic products and promos): migrate CRUD to SDK types and remove local interfaces
  package-lock.json
  src/app/(dashboard)/branches/[id]/edit/page.tsx
  src/app/(dashboard)/branches/[id]/page.tsx
  src/app/(dashboard)/branches/new/page.tsx
  src/app/(dashboard)/branches/page.tsx
  src/app/(dashboard)/products/page.tsx
  src/app/(dashboard)/users/[id]/edit/page.tsx
  src/app/(dashboard)/users/[id]/page.tsx
  src/app/(dashboard)/users/new/page.tsx
  src/app/(dashboard)/users/page.tsx
Labels: refactor

#32 features/adm/csv read file integration
  package-lock.json
  package.json
  src/app/(dashboard)/upload-files/page.tsx
  src/components/FileHelper/UploadCsv.tsx
  src/lib/utils/useCsvUploader.ts
Labels: feature

#35 Improve Dropdown Direction Based on Viewport Space & Adjust Table Overflow Behavior
  package-lock.json
  package.json
  src/app/(dashboard)/branches/page.tsx
  src/app/(dashboard)/coupons/page.tsx
  src/app/(dashboard)/products/page.tsx
  src/app/(dashboard)/users/page.tsx
  src/components/Dropdown.tsx
Labels: refactor

#37 Refactor Order Views: Add OrderInfoPanel and OrderProductList, Fix Dropdown Bug, and Improve Layout
  src/app/(dashboard)/orders/[id]/edit/page.tsx
  src/app/(dashboard)/orders/[id]/page.tsx
  src/app/(dashboard)/products/[id]/edit/page.tsx
  src/app/(dashboard)/products/[id]/presentations/[presentationId]/edit/page.tsx
  src/app/(dashboard)/products/[id]/presentations/new/page.tsx
  src/components/Dropdown.tsx
  src/components/OrderInfoPanel.tsx
  src/components/OrderProductList.tsx
Labels: bug, feature

#33 features/adm/pdf reports integration
  package-lock.json
  package.json
  public/Pharmatech_logo_reports.png
  src/app/(dashboard)/reports/inventory/page.tsx
  src/app/(dashboard)/reports/page.tsx
  src/app/(dashboard)/reports/sales/page.tsx
  src/components/Calendar.tsx
  src/components/FileHelper/PDFReportTemplate.tsx
  src/lib/utils/useFetchReport.ts
  src/styles/pdfStyles.ts
Labels: feature

#40 Add DashboardPage with StatCard component and date filtering
  package-lock.json
  package.json
  src/app/(dashboard)/dashboard/page.tsx
  src/app/(dashboard)/orders/[id]/edit/page.tsx
  src/app/(dashboard)/reports/sales/page.tsx
  src/app/login/page.tsx
  src/components/StatCard.tsx
  src/lib/utils/DateUtils.ts
Labels: feature

#41 Fix: Using translations for order statuses and colors
  src/app/(dashboard)/orders/[id]/edit/page.tsx
  src/app/(dashboard)/orders/[id]/page.tsx
  src/app/(dashboard)/orders/page.tsx
  src/lib/utils/orderTranslations.ts
Labels: bug

#44 feature/notify-order-update-only-by-socket
  package-lock.json
  src/app/(dashboard)/orders/[id]/edit/page.tsx
Labels: feature

#45 Feature/create quick actions
  package-lock.json
  package.json
  src/app/(dashboard)/branches/[id]/page.tsx
  src/app/(dashboard)/branches/page.tsx
  src/app/(dashboard)/categories/page.tsx
  src/app/(dashboard)/coupons/page.tsx
  src/app/(dashboard)/orders/page.tsx
  src/app/(dashboard)/presentations/page.tsx
  src/app/(dashboard)/products/page.tsx
  src/app/(dashboard)/profile/layout.tsx
  src/app/(dashboard)/promos/page.tsx
  src/app/(dashboard)/users/page.tsx
  src/components/ActionsTable.tsx
  src/components/Image/UploadedImage.tsx
  src/components/Table.tsx
  src/components/TableContainer.tsx
Labels: feature

#46 feature/display-sections-sidebar-by-role
  src/components/SideBar.tsx
Labels: feature

#47 feature/add-sales-chart-and-prediction
  src/app/(dashboard)/dashboard/page.tsx
  src/components/SideBar.tsx
Labels: feature

#49 Standardize validation schemas
  src/app/(dashboard)/users/[id]/edit/page.tsx
  src/app/(dashboard)/users/new/page.tsx
  src/lib/validations/categorySchema.ts
  src/lib/validations/editProfileSchema.ts
  src/lib/validations/loginSchema.ts
  src/lib/validations/newPresentationSchema.ts
  src/lib/validations/registerSchema.ts
  src/lib/validations/updatePasswordSchema.ts
Labels: refactor

#51 feature/create-inventory-list-page
  .husky/pre-commit
  .lintstagedrc
  package-lock.json
  package.json
  src/app/(dashboard)/branches/[id]/edit/page.tsx
  src/app/(dashboard)/branches/new/page.tsx
  src/app/(dashboard)/categories/[id]/edit/page.tsx
  src/app/(dashboard)/categories/new/page.tsx
  src/app/(dashboard)/coupons/new/page.tsx
  src/app/(dashboard)/inventories/page.tsx
  src/app/(dashboard)/presentations/[id]/edit/page.tsx
  src/app/(dashboard)/presentations/new/page.tsx
  src/app/(dashboard)/products/[id]/edit/page.tsx
  src/app/(dashboard)/products/[id]/presentations/[presentationId]/edit/page.tsx
  src/app/(dashboard)/products/[id]/presentations/new/page.tsx
  src/app/(dashboard)/products/new/page.tsx
  src/app/(dashboard)/profile/edit/page.tsx
  src/app/(dashboard)/profile/security/page.tsx
  src/app/(dashboard)/promos/[id]/edit/page.tsx
  src/app/(dashboard)/promos/new/page.tsx
  src/app/(dashboard)/reports/inventory/page.tsx
  src/app/(dashboard)/reports/sales/page.tsx
  src/app/(dashboard)/users/[id]/edit/page.tsx
  src/app/(dashboard)/users/new/page.tsx
  src/components/ActionsTable.tsx
  src/components/Input/Input.tsx
  src/components/Input/InventoryStock.tsx
  src/components/Navbar.tsx
  src/components/SideBar.tsx
  src/components/Table.tsx
  src/components/TableContainer.tsx
  src/context/AuthContext.tsx
Labels: feature

#54 Hotfix/order details amount
  package-lock.json
  package.json
  src/app/(dashboard)/orders/[id]/edit/page.tsx
  src/app/(dashboard)/orders/[id]/page.tsx
  src/app/(dashboard)/reports/inventory/page.tsx
  src/components/OrderProductList.tsx
Labels: bug

#50 Add GoogleMaps component and integrate with API
  package-lock.json
  package.json
  src/app/(dashboard)/branches/new/page.tsx
  src/components/GoogleMap/GoogleMap.tsx
  src/components/GoogleMap/UserAddressPoput.tsx
  src/lib/helpers/googleMapsConfig.ts
  src/lib/helpers/parsePlaceFromSear.ts
Labels: feature

#55 Feature/add more modules
  src/app/(dashboard)/lots/page.tsx
  src/app/(dashboard)/orders/[id]/edit/page.tsx
  src/app/(dashboard)/orders/[id]/page.tsx
  src/app/(dashboard)/orders/page.tsx
  src/app/(dashboard)/orders/requests/page.tsx
  src/app/(dashboard)/profile/page.tsx
  src/components/Navbar.tsx
  src/components/SideBar.tsx
Labels: bug
